name: build
on: [push, pull_request]
jobs:
  build:
    name: Build modpack
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Replace version number
        run: sed -i "s/version = \"dev\"/version = \"$(git describe --always)\"/g" pack.toml

      - name: refresh modpack
        run: packwiz refresh --build

      - name: upload artifact (packwiz)
        uses: actions/upload-artifact@v3
        with:
          name: "modpack (packwiz format)"
          path: | 
            pack.toml
            index.toml
            mods/

      - name: Cache Mods
        id: cache-mods
        uses: actions/cache@v3
        with:
          path: ~/.cache/packwiz/cache
          key: ${{ runner.os }}-packwiz-${{ hashFiles('index.toml') }}
          restore-keys: ${{ runner.os }}-packwiz

      - name: build modrinth format modpack
        run: packwiz modrinth export -o hackclub-modded.mrpack

      - name: upload artifact (modrinth)
        uses: actions/upload-artifact@v3
        with:
          name: "modpack (modrinth format)"
          path: "hackclub-modded.mrpack"

